ignore google sheets upload failures

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -18,10 +18,6 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    #- name: setup tmate
-    #  uses: mxschmitt/action-tmate@v2
-    #  if: matrix.os =='macos-latest'
-
     - name: set environment variables
       shell: bash
       run: |
@@ -311,7 +307,11 @@ jobs:
         }
 
         export SHEET=https://docs.google.com/spreadsheets/d/${{ secrets.RESULTS_SHEET_ID }}
-        python nmos-testing/utilities/run-test-suites/gsheetsImport/resultsImporter.py --credentials ${{ env.GDRIVE_CREDENTIALS }} --sheet "$SHEET" `join_with " --json " nmos-testing/results/${{ env.GITHUB_COMMIT }}-*.json`
+        python nmos-testing/utilities/run-test-suites/gsheetsImport/resultsImporter.py --credentials ${{ env.GDRIVE_CREDENTIALS }} --sheet "$SHEET" `join_with " --json " nmos-testing/results/${{ env.GITHUB_COMMIT }}-*.json` || echo "upload failed"
+
+    - name: setup tmate
+      uses: mxschmitt/action-tmate@v2
+      if: matrix.os =='macos-latest'
 
     - uses: actions/upload-artifact@v1
       with:
